p(DEFINE A (* 5 5))
(+ A A)
(DEFINE B (+ A (* 5 A)))
(+ B B)
(+ A (/ B 5))
(DEFINE (SQUARE X) (* X X))
(square 3)
(DEFINE l_square (LAMBDA (X) (* X X)))
(l_square 4)
(square 1001)
(square (square (square 1001)))
(+ (square 3) (square 4))
